### ISSUE TITLE
Podverse restarts constantly since last update

### ISSUE THREAD

**Issue by Porkepix** [podverse/podverse-rn#1992] opened 2023-10-22 06:50 UTC
**Describe the bug**

Since last update (4.14.0), Podverse is constantly starting by itself. Everytime, user close it from task manager, and a couple of seconds later it'll again restart and appears on foreground, indefinitely.

**To Reproduce**
1. Just have version 4.14.0 installed, and not running
2. It'll launch by itself
3. Kill it
4. It'll relaunch again
5. Repeat (even after reboot)

**Expected behavior**
It shouldn't restart constantly

**Smartphone (please complete the following information):**
 - Device: Sony Xperia
 - OS: Android Oreo (8.0) stock
 - App Version 4.14.0 from F-droid

**Comment by lovegaoshi** [comment] 2023-10-22 15:17
wow, this sounds like a terrible bug.
podverse introduced a wake-on-service feature that the app will be started when its service started. What you described sounds like this (an alternative scenario is in android auto, when the app is in use but killed, AA will attempt to start service again, bringing up the app then). but why is sony/android 8 doing this in particular? some logcat logs will be helpful.
also to @mitchdowney : I saw AA content update is disabled in f-droid versions. we can also disable this wake on service part all together in android native for f-droid. though i think in this particular scenario where the service is started somehow and probably is expected to support media playback, however RNTP will NOT be initialized to properly function, media playback will only be bugged anyways.
another thought is I did not filter intent at all in MusicService's oncreate; we probably can filter it to whatever sony's using here.

**Comment by lovegaoshi** [comment] 2023-10-22 18:29
Please especially check if you have this message repeatedly emitted with
logcat when the app keeps restarting:
https://github.com/lovegaoshi/react-native-track-player/blob/469fdb4b3509998dbc47f354cd6e2f061482497a/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L57

And keep an eye on any error log outputs.

I mistook the intent filter part, but we can still disable this wake for
fdroid builds all together to put a bandaid on this issue.

**Comment by mitchdowney** [comment] 2023-10-22 20:00
@Porkepix oof that is as bad of a bug as is possible 🤦‍♂️ I didn't see the bug in my tests, but honestly maybe I didn't even try closing F-Droid in my tests because I didn't think something like this could happen.

I'm asking the F-Droid Matrix room if we can somehow remove v4.14.0 from the F-Droid Store to stop distribution. Hopefully disabling the "wake on" service like @lovegaoshi describes will be enough to prevent the bug in the next release without introducing other problems. This is my top priority, although my Android knowledge is very limited so I'm not sure how much I can do without help.

**Comment by lovegaoshi** [comment] 2023-10-22 21:50
while i dont see errors on an emulator android 8 with fdroid:/ if this event below is indeed repeatably emitted, patching out wake on service will at least clear this issue. but it also does mean the service keeps crushing and restarting for whatever reason.
![Screenshot 2023-10-22 143721](https://github.com/podverse/podverse-rn/assets/106490582/6b8ec4ed-a09c-485d-bac4-d05a560782bf)

**Comment by mitchdowney** [comment] 2023-10-22 23:24
@lovegaoshi do you have any theories as to where the event is getting re-emitted from? Podverse specific logic, or RNTP itself?

Can the change be conditional to <= Android 8? Or should it just be disabled for all Android versions in our F-Droid anyway?

What is really confusing to me is how our app could be getting invoked when it seems like it should be closed already. As I understand, this event is being fired, and 

When I search for eglCreateContext online I found [this page](https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreateContext.xhtml). It _sounds_ like maybe it's related to draw over apps functionality? I also found [this SO answer](https://stackoverflow.com/a/59502468/2608858) about EGL. Still don't really understand it or why this event would fire on app close though...

The only meaningful changes to our Android logic (as opposed to our React Native logic) I can remember us doing would be config / xml updates, and Alecks Gates also worked on integrating UnifiedPush with Podverse for Android. I don't think his changes could be related but I'll ask him if he has any thoughts on this bug.

**Comment by lovegaoshi** [comment] 2023-10-23 01:13
@Porkepix by closing would you mean "swiping" up the app? Do you see the podverse mediasession notification "go away?"
and about the log this is the podverse download error I think, the "RNTP musicservice created" is the main problematic one that should have been the result of the wake behavior you described. I'll go ahead and patch out wake then cuz I can't tell what happened:(
@mitchdowney but podverse fdroid still uses my RNTP fork right?
I don't think its anything fdroid specific. it sounds like a system resource issue (I'm not sure why the service is getting recreated if app is killed:S). but how does podverse decide if a build is an fdroid build? 

I have a kindle 1st gen I can force install my app (same RNTP wake on service behavior) on to simulate the out of ram situation. though as far as simulator goes, 2gb ram never encountered this issue.
is there a smarter way to decide wake on service behavior i wonder?

**Comment by lovegaoshi** [comment] 2023-10-23 01:20
hmmm... without that log line I'm becoming skeptical if it fixes anything, but since it fits the behavior described I'll go ahead and do it. 
do you mind installing a debug apk and let us know if patching it out works?

**Comment by mitchdowney** [comment] 2023-10-23 01:56
@lovegaoshi 

> but podverse fdroid still uses my RNTP fork right?
> I don't think its anything fdroid specific. it sounds like a system resource issue (I'm not sure why the service is getting recreated if app is killed:S). but how does podverse decide if a build is an fdroid build?

Yes Podverse F-Droid is *almost* identical to the iOS / Google Play version (podverse-rn), but our F-Droid code is maintained is a separate repo [podverse-fdroid](https://github.com/podverse/podverse-fdroid), a fork of podverse-rn. The code base only has changes that are necessary for F-Droid compatibility (removing not fully FOSS packages, removing payment processors, removing tracking, etc).

There is a custom helper in the React Native called `checkIfFDroidAppVersion` we sometimes use, but mostly the non-compliant code is actually removed from the podverse-fdroid repo. Probably not the best approach with two repos but...I didn't know how else to do it.

**Comment by mitchdowney** [comment] 2023-10-23 02:10
@Porkepix 

> Now as for logs, when this happens the amount of logs emitted is absolutely massive. I've never seen so many, we talk about hundreds and hundreds of lines, most of them from processes names hard to identify (Fifth column in adb logcat -v threadtime)

yeah...honestly I have almost no grasp on how logging is being handled 🤦‍♂️ (or how it should be handled). Maybe this is creating problems for overall app performance? Should "reduce excessive logging" be its own Github issue?

**Comment by lovegaoshi** [comment] 2023-10-23 02:52
I can reproduce this problem in my kindle. so patching out the wake behavior is the way to go. i can get something tonight probably

**Comment by lovegaoshi** [comment] 2023-10-23 02:58
@mitchdowney my proposed solution is to add a Settings.canDrawOverlays check to the wake behavior. This has a catch that all android auto users must really enable the draw over apps permission to use android auto; but I think it's a fair thing to ask.

**Comment by mitchdowney** [comment] 2023-10-23 03:26
@lovegaoshi since we prompt all Android users for the Android Auto / Draw over apps permission, I think it's totally fine and maybe preferable that it only works when they have it enabled. If they don't enable it, but try to use Android Auto anyway, then they're likely to report a bug saying AA isn't working. Thanks again for the quick work on this!

**Comment by mitchdowney** [comment] 2023-10-23 04:36
@Porkepix @lovegaoshi Podverse for F-Droid 4.14.2-beta.1 is available for download. If I built it correctly, it contains lovegaoshi's fix for this issue. If you have a chance to download the apk and let us know if the bug is fixed we'd really appreciate it.

[Download F-Droid beta apk](https://files.podverse.fm/)

**Comment by lovegaoshi** [comment] 2023-10-23 12:31
About resource usage for my app I often clocks at 600-800MB RAM, podverse's dependencies are cleaner than mine but probably also hits >500MB RAM? RN apps are sorta like this, definitely not friendly to lower end phones. Unfortunately I can't even connect my low end kindle to adb anymore to read logcat. 
The service itself is not a new behavior from 4.14.0 - it was running like this before, I accidentally put a wake on it on ALL TIMES and now we started noticing it. Now as long as draw over apps permission is not granted (which for low end phones it is a wrong idea to run android auto I'd say), it should be just fine.

**Comment by schoetty** [comment] 2023-10-23 13:12
The problem with launching the app hits me even on android 14 when I toggle Aeroplane mode.

- App fully closed
- Aeroplane mode on/off
- App starts

**Comment by lovegaoshi** [comment] 2023-10-23 13:51
@schoetty learning something new everyday:facepalm I think this is an android 14 (or pixel specific?) behavior that when turning bluetooth on, all MediaBrowserServices were getting started (hence triggering the wake behavior). didnt see it on my S21 Android 13 yet, but pixel + android 14 yes.
I'll move this to another issue...

**Comment by mitchdowney** [comment] 2023-10-26 02:52
This should be in v4.14.2. I just sent it to F-Droid for release, but it takes about 1 week before it goes live. I'll close the issue, but we can reopen it if the issue persists in 4.14.2.

**Closed by mitchdowney** 2023-10-26 02:52 UTC
Labels: bug, ready to deploy
