### ISSUE TITLE
Not able to import OPML

### ISSUE THREAD

**Issue by drenina** [podverse/podverse-rn#1791] opened 2023-04-29 05:30 UTC
I am using Fdroid version 4.12.9 (78004) with Android 8.0, Sony Xperia.

I tried importing an OPML with jus a few podcasts, but it is not working, nothing is happeing. The app is directing my to the folder manager, I choose the opml file and get back to the importing setting, no import is started, no message displayed, nothing.

**Comment by mitchdowney** [comment] 2023-04-29 16:44
@drenina couple things here:

1) It appears you are using Android 8.0. Officially, Podverse only supports Android 11 and above. Podverse might still install on previous versions of Android, but in order to *officially* support older versions, we will need more help from the open source community. I have 3 jobs, and I just do not have enough time to investigate and debug the intricacies of older Android operating systems.

2) I'm not sure if the problem you are running into is due to Android 8 however. I just tried to import an OPML file using the F-Droid 4.12.9 version, and it imported successfully. Can you email the OPML you are trying to import to contact@podverse.fm? The first step to fixing a bug is always for devs to try reproducing the issue so we can debug it.

**Comment by mitchdowney** [comment] 2023-09-22 03:21
@erebion which version of Podverse are you using? It should be fixed as of 4.13.9...but that version is not yet available on F-Droid. We published it but there is about a 1 week delay before F-Droid publishes new releases.

https://github.com/podverse/podverse-rn/issues/1881

If you're using F-Droid and don't want to wait for it to be available on the store, you could download and install the APK here, but FYI you won't get automatic updates from F-Droid if you manually install by APK.

https://files.podverse.fm/

**Comment by mitchdowney** [comment] 2023-10-23 07:05
I think this fix was released in v4.13.9. @erebion if you continue to see issues please let us know. Thanks!

**Closed by mitchdowney** 2023-10-23 07:05 UTC
Labels: bug, ready to deploy

**Comment by mitchdowney** [comment] 2023-10-23 09:09
@erebion thanks for the quick response :)

**Comment by emrecio** [comment] 2026-07-12 18:57
Wondering if I can reopen this, because the same thing (identical symptoms) is happening on my Pixel 10. I was able to import the OPML on my desktop app, and other Android based podcasting apps, but not into Podverse. I am checking out a switch from my current android app.
