### ISSUE TITLE
Not able to stream sats

### ISSUE THREAD

**Issue by georgeorwell23** [podverse/podverse-rn#1786] opened 2023-04-26 23:25 UTC
Hello,

Since yesterday i'm not able to stream sats to most of the shows i'm listening to. 

Most of the shows also don't have the lightning icon anymore. 
My Alby wallet is still connected with Podverse. If i listen to for example the latest TFTC episode i can stream sats.
But when i listen to example bitcoin.review or the Stephan Livera podcast i'm not able to stream sats, but when i go to Fountain i can stream and boost sats. So something is going wrong it appeared yesterday, then i updated through the F-Droid store to the most recent version but that didn't fix it.
![IMG_20230427_012501](https://user-images.githubusercontent.com/108611713/234723347-f1144bb0-d5cb-4fe2-bfea-bdb471f63b87.jpg)

![Screenshot_20230427-011722](https://user-images.githubusercontent.com/108611713/234722732-3d5acac6-f0c3-45fb-9067-c048430a660a.png)

 - Pixel 6 running CalyxOS
 - App Version: 4.12.7 for F-Droid

**Comment by mitchdowney** [comment] 2023-04-27 03:20
@georgeorwell23 I'm sorry for the trouble! I just downloaded the F-Droid 4.12.7 version, and I was not able to reproduce the issue. Streaming sats and boostagrams are working for me. Perhaps this is an issue with Alby rather than an issue with Podverse? Do you have a default Alby wallet, or do have you connected your own node to Alby? It seems like that may sometimes make a difference.

Also, the lightning icons should not be connected to whether or not the Alby wallet is working for you, so it sounds like these are two separate issues. Can you share the name of some podcasts that you're expecting to see lightning icons next to but they're not appearing?

**Comment by georgeorwell23** [comment] 2023-04-27 07:25
@mitchdowney i'm using the default Alby wallet. From my end it looks like everything is correct and should be working. Is there something i can do?

Here are some podcasts with v4v enabled but can't stream sats and don't see the lightning icon:

• Bitcoin Rapid-Fire
• Swan Signal
• Bitcoin.Review
• Stephan Livera Podcast
• I Am Texas Slim
• We study billionaires

**Comment by mitchdowney** [comment] 2023-04-27 19:10
@georgeorwell23 ah thank you. It appears something has broken with the Podverse "sync with Podcast Index provided value tags" integration. I think something may have changed on their end? That is my guess because I can't think of any changes we would have made that would affect it. I'm asking Dave Jones about it on the [PI Mastodon](https://podcastindex.social/@mitch/110272337208956773).

**Comment by mitchdowney** [comment] 2023-04-27 20:11
@georgeorwell23 this should now be fixed on our backend. However, it will take ~12 hours for it to be completely fixed, as we have to reparse all the ~11,000 RSS feeds in Podcast Index that have value tags. Thanks again for alerting us of the issue.

I'm going to close the issue for now, but if the problem is still present after today, please lmk and we can reopen it.

**Closed** 2023-04-27 20:12 UTC
Labels: bug, ready to deploy
