### ISSUE TITLE
Allow rss podcasts to be marked as played

### ISSUE THREAD

**Issue by genebean** [podverse/podverse-rn#1520] opened 2022-12-19 03:12 UTC
**Is your feature request related to a problem? Please describe.**

It’s really difficult to keep track of what’s been listened to when you can’t mark a podcast as played. I have multiple podcasts that I pay for and get special versions of as a result. I expect to be able to track played status of them just like any other podcast. For reference, this has never been an issue in Castamatic (they even sync this with iCloud, I think) nor do I recall it being an issue in Overcast. 

**Describe the solution you'd like**

As a user I expect all podcasts to be treated equally and have the same features available. This includes tracking played status and cross device features. 

**Describe alternatives you've considered**

The only viable alternative to save my sanity on something like this is to return to another podcast app. 

**Additional context**

I remember us chatting about this and some concerns you had. I really think this is a table stakes feature since it’s done in the other apps I’ve used.

**Comment by mitchdowney** [comment] 2022-12-21 23:00
@genebean thanks for the request. This is a duplicate of #1240. I'll close this one.

**Closed by mitchdowney** 2022-12-21 23:00 UTC
Labels: duplicate, enhancement, blocked, v5
