### ISSUE TITLE
Correctly set the user agent for audio 

### ISSUE THREAD

**Issue by jamescridland** [podverse/podverse-rn#734] opened 2021-08-28 06:58 UTC
On Android, when you play this audio https://podverse.fm/episode/VjuVN__nBJ it says that the player is "React Native Player", which is presumably the default useragent for the player that you are using.

This should be set to something like `Podverse/1.0 +https://podverse.fm` or similar, to allow for Podverse plays to be correctly spotted by podcast analytics systems.

**Comment by jamescridland** [comment] 2021-08-28 07:03
Now I'm digging into the code - this was on a user-initiated play, not on an auto-download. Probably important to know!

**Comment by jamescridland** [comment] 2021-08-28 07:31
So, it looks as though the UserAgent is set by a `getAppUserAgent()` function in `/src/lib/utility.ts` but I don't understand how it reads the Config file, since I am at the very limit of my understanding here. `.env.example` appears to have nothing in the `USER_AGENT_PREFIX` section. I'm sorry, I'd have loved to have submitted a pull request with a fix, but I'm a bit at a loss as to what to do.

By the way - even more perfect to set the UA as `Podverse/1.0 Android/12 google.kukui/4 +https://podverse.fm` - i.e. the OS and the device type if that is possible to grab. I notice a `react-native-device-info` call in here which may have some of that information.

You're setting the useragent correctly on your RSS scraper, which is great to see.

**Comment by mitchdowney** [comment] 2021-09-22 03:39
Hey @jamescridland can you confirm if this is fixed? I think you correctly identified the issue, and hopefully Podverse user agents are passed on stream of episodes now.

**Comment by mitchdowney** [comment] 2021-10-10 01:47
I believe this was fixed. Going to close the issue. Can reopen if the issue is reported again.

**Closed by mitchdowney** 2021-10-10 01:47 UTC
