### ISSUE TITLE
Android- Progress bar seek not working properly (Make Clip)

### ISSUE THREAD

**Issue by KyleFDowney** [podverse/podverse-rn#1042] opened 2022-05-11 19:36 UTC
[https://peertube.podverse.fm/w/mkQ8fJ6jc77qBqw5aGQx6x](https://peertube.podverse.fm/w/mkQ8fJ6jc77qBqw5aGQx6x)

**Comment by mitchdowney** [comment] 2022-07-21 02:34
I can't reproduce this on my Pixel 4A...closing.

**Closed by mitchdowney** 2022-07-21 02:34 UTC
Labels: bug
