### ISSUE TITLE
cannot play downloaded episodes when offline

### ISSUE THREAD

**Issue by captain-egghead** [podverse/podverse-rn#1737] opened 2023-03-19 15:40 UTC
**Describe the bug**
Using podverse 4.12.3 from f-droid.

When no internet connection, e.g. when in airplane mode, trying to play downloaded episodes,
the play button turns into a red warning sign.

**To Reproduce**

1. Download some episodes, wait till finished, then turn on airplane mode.
2. Go to 'Episodes'
3. Choose Filter: "Downloaded" & Sort: "Latest"
4. Select an episode (tap the triangle below it)
5. tapping the play button on the bottom bar: no response
6. tapping the episode bar to expand to full screen:
    Play button changes into a red triangular warning sign

**Expected behavior**
Downloaded episodes should play normally, even in flight-mode.

**Screenshots**
![photo1679239752](https://user-images.githubusercontent.com/128306043/226186691-98eccadd-ae60-42f5-ba50-ab0731bb4725.jpeg)

**Smartphone (please complete the following information):**
 - OS: Android 11
 - 4.12.3 

**Additional context**
In the settings, Downloads is set "to external storage card"

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment] 2023-06-10 02:33
Thanks for the bug report. I think this is a duplicate of #1314. I'm going to copy and paste your message over there to consolidate discussion.

**Closed by mitchdowney** 2023-06-10 02:33 UTC
Labels: bug
