### ISSUE TITLE
Delete after playback finishes not working

### ISSUE THREAD

**Issue by illumiN8i** [podverse/podverse-rn#1593] opened 2023-01-07 05:27 UTC
**Describe the bug**
The "Delete after playback finishes" setting does not appear to be working. Episode finishes playing and green check appears, but episode is not deleted.

**To Reproduce**
1. Go to More->Settings->Downloads
2. Enable Delete after playback finishes setting
3. Play episode that is already downloaded to completion

**Expected behavior**
Episode download should be deleted after it is fully played.

**Screenshots**
![image](https://user-images.githubusercontent.com/44124235/211132666-dafe4bbe-5505-453a-98e8-4d889503046d.png)

**Smartphone**
 - Device: Google Pixel 5
 - OS: Android 13
 - App Version 4.10.5 Build 5160

**Comment by mitchdowney** [comment] 2023-02-06 21:44
This *might* be fixed as a side effect of v4.12.0, but I'll need to confirm.

**Comment by mitchdowney** [comment] 2023-02-11 03:34
This is still an issue, at least on iOS.

**Comment by mitchdowney** [comment] 2023-02-11 06:31
@illumiN8i this should be fixed in v4.12.1.

NOTE: the "delete after ended reached" feature will *mark* an episode for deletion, but will not delete the episode until the app is restarted. That is the intended behavior to prevent the file from being deleted too soon during an app session due to network connectivity errors out of our control.

**Comment by mitchdowney** [comment] 2023-02-14 02:00
@illumiN8i thanks for confirming!

**Closed by mitchdowney** 2023-02-14 02:00 UTC
Labels: bug, ready to deploy
