### ISSUE TITLE
Episode details can be cropped on lower resolution devices

### ISSUE THREAD

**Issue by amugofjava** [podverse/podverse-rn#499] opened 2021-02-22 18:43 UTC
Hi @mitchdowney,

Running Podverse on a device with a high resolution the episode details display correctly. On a 720p device the title and chapter can be cropped. Please see images below:

<img src="https://user-images.githubusercontent.com/5526902/108754272-a1075800-753d-11eb-88a7-237f48ceaae9.png" width="360"/>

<img src="https://user-images.githubusercontent.com/5526902/108754166-8339f300-753d-11eb-8bde-967f24ec2e39.jpg" width="360"/>

**Comment by mitchdowney** [comment] 2021-02-23 04:43
Hey thanks so much for testing it on multiple devices. Are you on the Beta build (3.0.3) or the build on the stores (3.0.2)? We tried fixing this in the 3.0.3 build.

If you're on Beta, I just realized tonight that I hadn't actually released the latest changes to Beta 🤦‍♂️ it was still on an old version (3.0.0). Sorry I thought these were getting automatically released, but there's a manual step I was forgetting.

**Comment by amugofjava** [comment] 2021-02-24 06:39
Hi @mitchdowney,

I've upgraded to 3.0.3 and tested again, but find it's still being cropped on my 720p device.

Thanks.

**Comment by mitchdowney** [comment] 2021-02-26 04:22
@amugofjava ahh bummer. So I just tried reproducing the issue on two devices. I'm actually not sure if they are 720p or not, but they're cheap/old and the only options I have right now.

On both the [RCA Reno](https://www.amazon.com/RCA-Reno-16GB-Android-Smartphone/dp/B0869S29LG/) and the Pixel 1 (Android Emulator), I could not reproduce the issue. However, I _could_ reproduce the issue on any device if I set the Display > Font Size above the default setting. This is an oversight on my part, as some of the visual components will break if the font size increases. I went ahead and disabled the font size increase on the PlayerScreen and also in the MiniPlayer bar. This prevents the text from being cut off, but I'm not sure if this fix will apply for the issue with your phone.

If your 720p phone does not use larger than default font sizes, what device are you using? We'll need to track down a 720p phone to debug the issue.

**Comment by amugofjava** [comment] 2021-02-26 06:49
Hi @mitchdowney,

My phone is an aging WileyFox Swift. Checking the specs the screen is 720 x 1280. It's pretty much on default settings so I haven't made any adjustments to the font scaling. 

<img width="300" src="https://user-images.githubusercontent.com/5526902/109265246-20c34a00-77fe-11eb-976f-36e8b366581e.png"/>
<img width="300" src="https://user-images.githubusercontent.com/5526902/109265257-24ef6780-77fe-11eb-91b1-66be717bacc5.png"/>

**Comment by mitchdowney** [comment] 2021-03-20 18:50
@amugofjava are you still seeing this issue in the latest version? And are you using Android or F-Droid? (I'm not sure if F-Droid has this update yet.)

**Comment by amugofjava** [comment] 2021-03-20 19:01
Hey @mitchdowney,

I've just downloaded version 3.0.5 Build 734 and it's still doing it for me. Scaling for multiple screen sizes is such a pain.

![Screenshot_20210320-185611](https://user-images.githubusercontent.com/5526902/111882668-a924ad00-89ae-11eb-8c55-16230ccc11e1.png)

**Comment by mitchdowney** [comment] 2022-01-25 04:27
@amugofjava I just tested the player with a virtual Galaxy Nexus, which has a resolution of 720 x 1280, and says "xhdpi", and the player screen layout fit on the screen:

![image](https://user-images.githubusercontent.com/2262919/150910858-d8d6f790-6257-40ce-8294-2951815bac09.png)

![Screenshot_1643084701](https://user-images.githubusercontent.com/2262919/150910877-a23e7e42-6977-4ea3-9470-dc59f1835f63.png)

Maybe the pixel density is too fine? I'll try finding a virtual device with a larger pixel density...

**Comment by mitchdowney** [comment] 2022-01-25 04:33
@amugofjava sorry to bug you, but if you still have your device, could you test and see if Podcasting 2.0 art still cuts off?

**Comment by mitchdowney** [comment] 2022-02-14 04:28
@amugofjava good to hear!

@kreonjr we can close this issue but...I'm think I might have made the podcast art too small on larger phones while fixed this issue. I think in #919 we have to make the album art styles more responsive for different screen sizes.

**Closed by mitchdowney** 2022-02-14 04:28 UTC
