### ISSUE TITLE
Items not being deleted

### ISSUE THREAD

**Issue by alienrobotarmy** [podverse/podverse-rn#2019] opened 2023-11-01 21:12 UTC
My phone shows 60+ GB in use by Podverse, despite having 0 downloaded shows. All podcasts in Podverse show “0 downloaded”. 

I’ve set the limit to 1 episode under Settings -> Downloads and clicked “Delete downloads” button but the storage isn’t free’d

I also tried to delete cache under Settings -> Other -> Delete Cache but this has no impact on the amount of storage being used by Podverse

**To Reproduce**
Listen to a bunch of podcasts   

**Expected behavior**
Storage to be free’d up. 

**Screenshots**
![IMG_4669](https://github.com/podverse/podverse-rn/assets/8185411/91419afd-117f-4cf0-97d8-70cc8912d506)
![IMG_4668](https://github.com/podverse/podverse-rn/assets/8185411/65e71d96-e844-4a54-aa76-3d60d98ba117)
![IMG_4666](https://github.com/podverse/podverse-rn/assets/8185411/e0bf036e-22f6-4e1a-9f96-8fad4f12410c)
![IMG_4667](https://github.com/podverse/podverse-rn/assets/8185411/66765a17-3b78-4f3a-b048-289283abf1a1)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 16.6.1
 - App Version 4.14.2

**Additional context**

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment] 2023-11-03 04:04
hey @alienrobotarmy I'm sorry, that's a terrible bug :(

We do have some fixes we need to make in 4.14.3 for *displaying* downloaded episodes, but the "Delete episodes" button should be wiping out everything for you even if they don't appear.

I'm not sure what could cause this, other than possibly the app's internal reference to the downloaded files directory has somehow become broken.

Are you on the Podverse Beta tester track by chance? Or have you switched from our Beta to our public app version recently? I wonder if an update from one track to the other could cause this.

I'll assign this to me and see if I can identify any issues.

**Comment by mitchdowney** [comment] 2023-11-03 05:01
@alienrobotarmy unfortunately I am not able to reproduce the issue, and I likely will not have a solution in the next release 😞

The only remediation option I can think of at this time is to delete and reinstall the app, and then verify the storage increases and decreases as expected on the device's Storage screen when you delete or download episodes.

Sorry deleting and reinstalling is a worst-case type of remediation. If you have a Podverse Premium membership, your subscriptions should automatically restore after you reinstall the app and you login. If you don't have Premium but would like it, you can email us at contact@podverse.fm and we'll give you a free membership.

**Comment by alienrobotarmy** [comment] 2023-11-05 22:17
After deleting the app I can confirm that the 62GB in use by Podverse was deleted. I was able to reinstall and login with all my settings!

**Comment by mitchdowney** [comment] 2023-11-28 07:31
@alienrobotarmy it turns out the references we save (in AsyncStorage) that point to the downloaded files were overwriting each other when 2+ episodes finish downloading at the same time. I think this might explain why so many people have reported the app takes up a lot of storage, and only frees it up after deleting and reinstalling the app.

I tried adding a fix in v4.15.0 by adding a queue to our "save downloaded file" operation, so only one finished download will be processed at a time, so the references in AsyncStorage don't override each other.

I'm going to close this issue, but can reopen it if it keeps getting reported.

https://github.com/podverse/podverse-rn/commit/b331c5e4d398543fb708fc3627badc499bf4c878

**Closed** 2023-11-28 07:31 UTC
Labels: bug, ready to deploy
