### ISSUE TITLE
Skip forward and Back from headsets not working

### ISSUE THREAD

**Issue by RonV42** [podverse/podverse-rn#1794] opened 2023-04-29 12:42 UTC
Running on Android 11 when setting the option in the App:

Skip track's buttons jump time on headsets and the lockscreen. 

Pressing the skip forward or skip back on the headset nothing happens, I have uninstalled, and reinstalled the app, turned the feature off and on and still can't get any of my headsets or car Bluetooth integration to skip ahead in any podcast.

**To Reproduce**
1. Go to More /  Settings / Player 
2. Turn on "Skip-track buttons jump time on headsets and the lockscreen"
3. Connect Bluetooth and start listening to a podcast
4. Press skip forward or back an the podcast doesn't skip in any direction.

**Expected behavior**
I expect the currently played podcast to skip forward by the number of seconds on the setting or skip back by the number of seconds on the setting

**Screenshots**
![image](https://user-images.githubusercontent.com/34961476/235302880-8134b028-00ad-4930-ab68-dc48e9356bf4.png)

**Smartphone (please complete the following information):**
 - Device: REVVL 5G (T-Mobile) TCL T790W
 - OS:  Android 11 Build RKQ1.210209.002, Software version 7D64UM40
 - App Version:  4.12.9 for F-Droid

**Additional context**

I have tried this with the following Bluetooth Devices:

Jabra 85T
Jabra 65T
HondaSync Bluetooth Audio
Ford Sync Bluetooth Audio
Amazon EchoDot (voice command skip forward)
Various JBL speakers my kids have with physical buttons to skip forward and back.

**Comment by mitchdowney** [comment] 2023-04-29 16:51
@RonV42 thanks for this detailed bug report! When you say "I have tried this with the following Bluetooth Devices:", does the feature *fail* on all of those devices as well?

**Comment by RonV42** [comment] 2023-04-29 22:56
> @RonV42 thanks for this detailed bug report! When you say "I have tried this with the following Bluetooth Devices:", does the feature _fail_ on all of those devices as well?

Yes doesn't work on any of those devices, that is every Bluetooth device in my home.

**Comment by mitchdowney** [comment] 2023-05-08 03:47
@RonV42 as @XceptN pointed out, this issue is a duplicate of #1794. Please follow that issue for future updates.

**Closed by mitchdowney** 2023-05-08 03:47 UTC
Labels: bug, help wanted

**Comment by mitchdowney** [comment] 2023-05-09 06:42
@XceptN 🤦‍♂️ yes correct, thank god someone knows what is going on around here
