### ISSUE TITLE
iPad OS Testflight split view not updating pan size.

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-rn#1449] opened 2022-11-26 04:35 UTC
**Describe the bug**
The pane size does not resize to current window size.

**To Reproduce**
put podverse into split view
use player or show tile view in pod cast

**Expected behavior**
Re-sizing of elements to fit pane

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9
 - OS: 16.1
 - App Version 4.7.0 (1854)
 
**Additional context**
Same behavior in when using a non-floating split screen

Please feel free to [join our Discord](https://discord.gg/6HkyNKR) and chat with us in the #dev channel if you'd like to work on this.

**Comment by mitchdowney** [comment] 2022-11-26 05:45
A fix for this should be in v4.7.1 (basically a duplicate of #1450).

**Closed** 2022-12-07 05:28 UTC
Labels: bug, ready to deploy
