### ISSUE TITLE
Podcastindex.org split receiving a 401 during boostagram

### ISSUE THREAD

**Issue by elreydetoda** [podverse/podverse-rn#1221] opened 2022-09-17 15:37 UTC
**Describe the bug**
When attempting to send a boostagram to @JupiterBroadcasting (JB) podcasts, I'm getting a 401 response when sending to the podcastindex.org split.

**To Reproduce**
1. Go to and play JB episode (my screenshot is of [this one](https://podverse.fm/episode/WW8_4_c5v) in the app)
2. Click on "BOOSTAGRAM"
3. Type message
4. Click "Send" button
5. Get 401 error

**Expected behavior**
No 401 error, and split of 22 SATs being sent to the Podcastindex.org.

**Screenshots**

![image](https://user-images.githubusercontent.com/10230166/190864566-882007be-36f1-462e-81c2-8ff94de04e8c.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9 (SM-G960U)
 - OS: Android 10
 - App Version: 4.6.2 (from F-droid)

**Additional context**
Mentioned this on the Discord chat: https://discord.com/channels/467863863098998795/858034929572118558/1020698273683603566

I can validate I'm not sending the full 2222 SATs I'm trying to send from my Alby wallet transaction amount being sent.

![image](https://user-images.githubusercontent.com/10230166/190864807-574092d7-723e-4577-ad1a-57778bd14442.png)

**Comment by elreydetoda** [comment] 2022-09-17 22:34
Potentially related #1190

**Comment by mitchdowney** [comment] 2022-09-24 00:39
A fix for this (along with #1246) should be in v4.6.7-beta.2. #1261

**Comment by mitchdowney** [comment] 2022-09-24 00:43
@elreydetoda I put the above comment in the wrong Github issue 🤦‍♂️ 

Still...we've been unable to reproduce a 401 error in our tests so far. There _are_ however V4V network request fixes in #1246, so this _might_ have fixed #1221 in the process.

I'll close this for now but please lmk if you see a 401 again and we can reopen it.

**Closed by mitchdowney** 2022-09-24 00:43 UTC
Labels: bug, ready to deploy
